sonar.projectKey=sub-aina_subaina-mern-10pshine
sonar.organization=sub-aina

sonar.sources=notes-app/backend/src,notes-app/frontend/src
sonar.tests=notes-app/backend/test,notes-app/frontend/src
sonar.test.inclusions=**/*.test.js,**/*.test.jsx
sonar.exclusions=**/node_modules/**,**/build/**,**/dist/**,**/coverage/**

sonar.javascript.lcov.reportPaths=notes-app/backend/coverage/lcov.info,notes-app/frontend/coverage/lcov.info

sonar.sourceEncoding=UTF-8
